window.modoApi = true;
async function enviarApi(acao, dados) { const resposta = await fetch(`../api.php?acao=${acao}`, { method: 'POST', credentials: 'same-origin', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(dados) }); return resposta.json(); }
function mostrarErro(form, mensagem) { let aviso = form.querySelector('.form-erro'); if (!aviso) { aviso = document.createElement('p'); aviso.className = 'form-erro'; form.prepend(aviso); } aviso.textContent = mensagem; }
function limparErrosCampos(form) { form.querySelectorAll('.mensagem-campo').forEach(e => e.remove()); form.querySelectorAll('.invalido').forEach(e => e.classList.remove('invalido')); }
function mostrarErroCampo(form, campo, mensagem) { limparErrosCampos(form); const input = form.elements[campo]; if (!input) return mostrarErro(form, mensagem); input.classList.add('invalido'); const texto = document.createElement('small'); texto.className = 'mensagem-campo'; texto.textContent = mensagem; input.closest('.senha-wrapper, .input-group').appendChild(texto); input.focus(); mostrarErro(form, 'Revise o campo destacado.'); }
function cpfValidoCliente(valor) { const cpf = String(valor || '').replace(/\D/g, ''); if (cpf.length !== 11 || /^(\d)\1{10}$/.test(cpf)) return false; for (let d = 9; d < 11; d++) { let soma = 0; for (let i = 0; i < d; i++) soma += Number(cpf[i]) * (d + 1 - i); if (Number(cpf[d]) !== ((10 * soma) % 11) % 10) return false; } return true; }
function validarCadastroCliente(form) { const d = Object.fromEntries(new FormData(form)); const regras = [['nome', String(d.nome || '').trim().length >= 3, 'Informe um nome com pelo menos 3 caracteres.'], ['cpf', cpfValidoCliente(d.cpf), 'Informe um CPF válido.'], ['email', /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(d.email || ''), 'Informe um e-mail válido.'], ['senha', String(d.senha || '').length >= 6, 'A senha deve possuir pelo menos 6 caracteres.'], ['telefone', String(d.telefone || '').replace(/\D/g, '').length >= 10, 'Informe um telefone com DDD.']]; const erro = regras.find(r => !r[1]); if (erro) { mostrarErroCampo(form, erro[0], erro[2]); return false; } limparErrosCampos(form); return true; }
function iniciarAutenticacaoApi() {
  document.querySelectorAll('.toggle-password').forEach(b => b.addEventListener('click', () => { const c = document.getElementById(b.dataset.target); c.type = c.type === 'password' ? 'text' : 'password'; }));
  const login = document.getElementById('loginForm'); if (login) login.addEventListener('submit', async e => { e.preventDefault(); try { const r = await enviarApi('login', Object.fromEntries(new FormData(login))); if (!r.sucesso) return mostrarErro(login, r.mensagem); sessionStorage.setItem('sjcar-usuario', JSON.stringify(r.usuario)); location.assign('painel.html'); } catch { mostrarErro(login, 'Não foi possível conectar ao servidor.'); } });
  const cadastro = document.getElementById('cadastroForm'); if (cadastro) cadastro.addEventListener('submit', async e => { e.preventDefault(); if (!validarCadastroCliente(cadastro)) return; try { const r = await enviarApi('cadastro', Object.fromEntries(new FormData(cadastro))); if (!r.sucesso) return r.campo ? mostrarErroCampo(cadastro, r.campo, r.mensagem) : mostrarErro(cadastro, r.mensagem); alert('Cadastro realizado com sucesso!'); location.href = 'login.html'; } catch { mostrarErro(cadastro, 'Não foi possível conectar ao servidor.'); } });
}
if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', iniciarAutenticacaoApi); else iniciarAutenticacaoApi();
