CREATE DATABASE IF NOT EXISTS faculdade_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE faculdade_db;

CREATE TABLE IF NOT EXISTS anunciante (
  IdAnunciante INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  Nome VARCHAR(120) NOT NULL,
  CPF CHAR(11) NOT NULL UNIQUE,
  Email VARCHAR(160) NOT NULL UNIQUE,
  SenhaHash VARCHAR(255) NOT NULL,
  Telefone VARCHAR(20) NOT NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS anuncio (
  IdAnuncio INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  IdAnunciante INT UNSIGNED NOT NULL,
  Marca VARCHAR(60) NOT NULL,
  Modelo VARCHAR(80) NOT NULL,
  AnoFabricacao SMALLINT UNSIGNED NOT NULL,
  Cor VARCHAR(40) NOT NULL,
  Quilometragem INT UNSIGNED NOT NULL,
  Descricao TEXT NOT NULL,
  Valor DECIMAL(12,2) NOT NULL,
  Estado CHAR(2) NOT NULL,
  Cidade VARCHAR(100) NOT NULL,
  DataHora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_anuncio_anunciante FOREIGN KEY (IdAnunciante) REFERENCES anunciante(IdAnunciante) ON DELETE CASCADE,
  INDEX idx_anuncio_filtros (Marca, Modelo, Cidade),
  INDEX idx_anuncio_data (DataHora)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS foto (
  IdFoto INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  IdAnuncio INT UNSIGNED NOT NULL,
  NomeArquivo VARCHAR(255) NOT NULL,
  CONSTRAINT fk_foto_anuncio FOREIGN KEY (IdAnuncio) REFERENCES anuncio(IdAnuncio) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS interesse (
  IdInteresse INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  IdAnuncio INT UNSIGNED NOT NULL,
  Nome VARCHAR(120) NOT NULL,
  Telefone VARCHAR(20) NOT NULL,
  Mensagem TEXT NOT NULL,
  Lido TINYINT(1) NOT NULL DEFAULT 0,
  DataHora DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_interesse_anuncio FOREIGN KEY (IdAnuncio) REFERENCES anuncio(IdAnuncio) ON DELETE CASCADE,
  INDEX idx_interesse_anuncio (IdAnuncio)
) ENGINE=InnoDB;
